### ISSUE TITLE
Server - npm start 

### ISSUE THREAD

**Issue by YodaSpock** [YodaSpock/WingedVelociraptors#5]
![Capture](https://user-images.githubusercontent.com/22249380/80855312-dbe27d00-8c05-11ea-8a14-902656a7bb22.PNG)

**Comment by YodaSpock** [comment]
I'm going to give this a look first

**Comment by YodaSpock** [comment]
npm install on the server fixed the issue, I'm disappointed with myself

**Comment by danielisgr8** [comment]
I'm gonna jump out the Eiffel Tower. I will literally spend the money on a plane ticket just to fly to France and do this.
